### ISSUE TITLE
Glitch Hello World `Could not find node 7.7.1, using 6.12.3`

### ISSUE THREAD

**Issue by hally9k** [probot/friction#24]
I've just followed the step by step intro readme on Glitch and the example doesn't run unfortunately.

I get the following in the activity log:

```Could not find node 7.7.1, using 6.12.3
Node.js version >=7.7 is required. You have v6.12.3.
```

May well be a Glitch issue but thought I'd flag it up anyway.

Very excited to play with this, I hope to hear from you soon!

**Comment by j-f1** [comment]
Try putting `"engines": { "node": "8.x" }` in your `package.json`.

**Comment by tcbyrd** [comment]
Hey @hally9k! I ran into this earlier. You have to specify the version of node in `package.json`. Something like this should work:

```
 "engines": {
    "node": "8"
  },
```
It looks like all the `7.*` versions of Node got removed from Glitch, so we'll need to update the base Glitch app so it uses a newer version.

FYI, there's a Glitch App that lists all the current versions of Node on Glitch. So meta:
https://nodeversions.glitch.me/

**Comment by JasonEtco** [comment]
FWIW, we should have that in the Glitch base app anyway, since v8 is LTS (`8.9.4`)

**Comment by hally9k** [comment]
Cheers guys (node 8 works), the README is a little sparse too. It says that we'll come back to changing the webhook url later and then doesn't mention it again. What am I supposed to set this to? I'm a little merky on how the pieces fit together at the moment...

**Comment by hally9k** [comment]
@JasonEtco  Updating the probot version to latest would be good too...

**Comment by hally9k** [comment]
Got it hooked up but keep getting the following error everytime the webhook fires:

```
[90m10:10:16.568Z[39m [31mERROR[39m probot: [36mfn.call is not a function[39m[90m (id=a872defc-c38f-413a-b3f4-907fc96a813d)[39m

[90m  TypeError: fn.call is not a function

      at /app/node_modules/express-async-errors/index.js:17:20

      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

      at /app/node_modules/express/lib/router/index.js:284:7

      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

      at next (/app/node_modules/express/lib/router/index.js:275:10)

      at /app/node_modules/probot/lib/middleware/logging.js:33:5

      at /app/node_modules/express-async-errors/index.js:17:20

      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

      at /app/node_modules/express/lib/router/index.js:284:7

      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

      at next (/app/node_modules/express/lib/router/index.js:275:10)

      at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)

      at /app/node_modules/express-async-errors/index.js:17:20

      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

      at /app/node_modules/express/lib/router/index.js:284:7

      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

      at next (/app/node_modules/express/lib/router/index.js:275:10)

      at query (/app/node_modules/express/lib/middleware/query.js:45:5)

      at /app/node_modules/express-async-errors/index.js:17:20

      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

      at /app/node_modules/express/lib/router/index.js:284:7

      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

      at next (/app/node_modules/express/lib/router/index.js:275:10)

      at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)

      at Function.handle (/app/node_modules/express/lib/application.js:174:10)

      at Server.app (/app/node_modules/express/lib/express.js:39:9)

      at emitTwo (events.js:126:13)

      at Server.emit (events.js:214:7)

      at parserOnIncoming (_http_server.js:602:12)

      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)

[39m[90m10:10:16.570Z[39m [31mERROR[39m probot: [36mfn.call is not a function[39m[90m (id=8f00347c-b921-42c0-8a4d-8eb33b813625)[39m

[90m  TypeError: fn.call is not a function

      at /app/node_modules/express-async-errors/index.js:17:20

      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

      at /app/node_modules/express/lib/router/index.js:284:7

      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

      at next (/app/node_modules/express/lib/router/index.js:275:10)

      at /app/node_modules/probot/lib/middleware/logging.js:33:5

      at /app/node_modules/express-async-errors/index.js:17:20

      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

      at /app/node_modules/express/lib/router/index.js:284:7

      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

      at next (/app/node_modules/express/lib/router/index.js:275:10)

      at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)

      at /app/node_modules/express-async-errors/index.js:17:20

      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

      at /app/node_modules/express/lib/router/index.js:284:7

      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

      at next (/app/node_modules/express/lib/router/index.js:275:10)

      at query (/app/node_modules/express/lib/middleware/query.js:45:5)

      at /app/node_modules/express-async-errors/index.js:17:20

      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)

      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)

      at /app/node_modules/express/lib/router/index.js:284:7

      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)

      at next (/app/node_modules/express/lib/router/index.js:275:10)

      at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)

      at Function.handle (/app/node_modules/express/lib/application.js:174:10)

      at Server.app (/app/node_modules/express/lib/express.js:39:9)

      at emitTwo (events.js:126:13)

      at Server.emit (events.js:214:7)

      at parserOnIncoming (_http_server.js:602:12)

      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)

[39m[90m10:10:16.574Z[39m [32m INFO[39m probot: [36mPOST / 404 - 6.14 ms[39m[90m (id=a872defc-c38f-413a-b3f4-907fc96a813d)[39m

[90m10:10:16.574Z[39m [32m INFO[39m probot: [36mPOST / 404 - 4.57 ms[39m[90m (id=8f00347c-b921-42c0-8a4d-8eb33b813625)[39m

[90m10:10:16.577Z[39m [31mERROR[39m probot: [36mNot Found[39m

[90m  Error: Not Found

      at Request.callback (/app/node_modules/superagent/lib/node/index.js:696:15)

      at IncomingMessage.parser (/app/node_modules/superagent/lib/node/index.js:906:18)

      at emitNone (events.js:111:20)

      at IncomingMessage.emit (events.js:208:7)

      at endReadableNT (_stream_readable.js:1055:12)

      at _combinedTickCallback (internal/process/next_tick.js:138:11)

      at process._tickDomainCallback (internal/process/next_tick.js:218:9)

[39m[90m10:10:16.578Z[39m [31mERROR[39m probot: [36mNot Found[39m

[90m  Error: Not Found

      at Request.callback (/app/node_modules/superagent/lib/node/index.js:696:15)

      at IncomingMessage.parser (/app/node_modules/superagent/lib/node/index.js:906:18)

      at emitNone (events.js:111:20)

      at IncomingMessage.emit (events.js:208:7)

      at endReadableNT (_stream_readable.js:1055:12)

      at _combinedTickCallback (internal/process/next_tick.js:138:11)

      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Its a simple demo app I'm trying to run... 

```
module.exports = (robot) => {
  // Your code here
  console.log('Booom! The Reviewer Notification app was loaded!');
  robot.on('pull_request', (context) => {
    // `context` extracts information from the event, which can be passed to
    console.log(context.payload)
  })
}

```

**Comment by laughedelic** [comment]
@hally9k I got the same exact error trying to deploy to Glitch and Now and I opened #25, because I wasn't sure this issue is related (Now doesn't have this problem with the node version).

**Comment by tcbyrd** [comment]
This looks to be something brought in from a recent release of `express-async-errors` (one of Probot's dependencies). For now you can downgrade to 4.1.0 of Probot, which doesn't have that dependency. We'll get a fix together ASAP.

**Comment by bkeepers** [comment]
The glitch app has been updated to use node 8 by default, and I just pushed out probot 5.0.1 which should have a temporary fix for the `express-async-errors` issue.
